development:
  db:
    name: app-backend
    host: localhost
    port: 3306
    user: root
    password: imqi1@db

production:
  db:
    name: demo
    host: 127.0.0.1
    port: 3306
    user: demo
    password: demo
