development:
  db:
    name: app-backend
    host: localhost
    port: 3306
    user: root
    password: imqi1@db
  frontend: http://localhost:5173

production:
  db:
    name: demo
    host: 127.0.0.1
    port: 3306
    user: demo
    password: demo
  frontend: https://frontend-demo.qi1.website

qweather_api_key: 8e331c0c65774fa4bc8e8ac4ef976554
